---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: wasm-image-app
---
# Volume (Persistent Volume Claim)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
  namespace: wasm-image-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: wasm-image-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: mingdodev/wasm-image-api:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/data/images
              name: images-storage
      volumes:
        - name: images-storage
          persistentVolumeClaim:
            claimName: images-pvc
---
# 3. API Service
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: wasm-image-app
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
# Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: wasm-image-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: mingdodev/wasm-image-processor:2.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: wasm-image-app
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
